services:
  mongodb:
    container_name: kursinfo-api-mongo
    image: mongo:4.0.0
    ports:
      - 27018:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=axel
      - MONGO_INITDB_ROOT_PASSWORD=axel
