trigger: none
pr: none

parameters:
  - name: imageTag
    type: string
    displayName: New image tag in production

variables:
  - group: studadm-general-params
  - name: imageName
    value: kursinfo-api
  - name: parametersFileName
    value: prod.parameters.json

resources:
  repositories:
    - repository: stratus-templates
      type: git
      name: Cloud Excellence Team/stratus-templates
      ref: main

pool:
  vmImage: 'ubuntu-latest'

extends:
  template: templates/security/security-scans.yml@stratus-templates
  parameters:
    break: false
    steps:
    - template: templates/app-service/update-image.yml@stratus-templates
      parameters:
        parametersFileName: $(parametersFileName)
        imageName: $(imageName)
        tag: ${{ parameters.imageTag }}
