trigger: none
pr: none

parameters:
  - name: imageTag
    type: string
    displayName: New image tag in production

variables:
  - group: studadm-general-params
  - group: studadm-spoke1-prod
  - name: appName
    value: kursinfo-api-prod
  - name: imageName
    value: kursinfo-api
  - name: parametersFileName
    value: prod.parameters.json

resources:
  repositories:
    - repository: stratus-templates
      type: git
      name: Cloud Excellence Team/stratus-templates
      ref: main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - template: templates/app-service/update-image.yml@stratus-templates
    parameters:
      parametersFileName: $(parametersFileName)
      appName: $(appName)
      imageName: $(imageName)
      tag: ${{ parameters.imageTag }}
      isApi: true
